# Generated by Django 4.2.9 on 2024-02-18 21:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funfacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funfacts',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
